"""Add multi-tenant support

Revision ID: a3471c834318
Revises: 569522b7e4f1
Create Date: 2026-03-22 16:54:00.164816

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a3471c834318'
down_revision = '569522b7e4f1'
branch_labels = None
depends_on = None


def upgrade():
    # 1. TẠO BẢNG hotels
    op.create_table('hotels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('logo_url', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )

    # 2. TẠO KHÁCH SẠN MẶC ĐỊNH
    op.execute("INSERT INTO hotels (name, slug, is_active) VALUES ('Khách sạn Trung tâm', 'central', 1)")

    # 3. THÊM hotel_id VÀ NOT NULL (Sử dụng raw SQL cho chắc chắn)
    tables = [
        'rooms', 'customers', 'bookings', 'booking_rooms', 'booking_services',
        'services', 'payments', 'price_rules', 'inventory_items', 'expenses', 'users'
    ]
    
    for table in tables:
        print(f"Adding hotel_id to {table}...")
        op.add_column(table, sa.Column('hotel_id', sa.Integer(), nullable=True))
        op.create_foreign_key(f'fk_{table}_hotel', table, 'hotels', ['hotel_id'], ['id'])
        op.execute(f"UPDATE {table} SET hotel_id = 1")
        if table != 'users': # users có thể để nullable để super admin ko thuộc hotel nào
            op.alter_column(table, 'hotel_id', existing_type=sa.Integer(), nullable=False)

    # 4. THÊM is_super_admin CHO users
    op.add_column('users', sa.Column('is_super_admin', sa.Boolean(), nullable=True))
    op.execute("UPDATE users SET is_super_admin = 1 WHERE username = 'admin'")

    # 5. CÁC THAY ĐỔI KIỂU DỮ LIỆU CẦN THIẾT (ENUM -> VARCHAR)
    op.alter_column('rooms', 'room_type', existing_type=mysql.VARCHAR(50), type_=sa.String(20))
    op.alter_column('rooms', 'status', existing_type=mysql.VARCHAR(50), type_=sa.String(20))
    # Chuyển types khác nếu cần
    op.alter_column('booking_rooms', 'rental_type', existing_type=mysql.VARCHAR(50), type_=sa.String(20))
    op.alter_column('booking_rooms', 'status', existing_type=mysql.VARCHAR(50), type_=sa.String(20))
    op.alter_column('bookings', 'payment_status', existing_type=mysql.VARCHAR(50), type_=sa.String(20))
    op.alter_column('bookings', 'status', existing_type=mysql.VARCHAR(50), type_=sa.String(20))
    op.alter_column('payments', 'payment_method', existing_type=mysql.VARCHAR(50), type_=sa.String(50))


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('fs_uniquifier',
               existing_type=sa.String(length=64),
               type_=mysql.VARCHAR(length=45),
               nullable=True)
        batch_op.alter_column('role',
               existing_type=sa.String(length=20),
               type_=mysql.ENUM('admin', 'staff'),
               existing_nullable=True,
               existing_server_default=sa.text("'staff'"))
        batch_op.drop_column('is_super_admin')
        batch_op.drop_column('hotel_id')

    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('price',
               existing_type=sa.Integer(),
               type_=mysql.DECIMAL(precision=10, scale=2),
               existing_nullable=False)
        batch_op.drop_column('hotel_id')

    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index(batch_op.f('room_number'), ['room_number'], unique=True)
        batch_op.alter_column('clean_status',
               existing_type=sa.String(length=20),
               type_=mysql.ENUM('cleaned', 'dirty'),
               existing_nullable=True,
               existing_server_default=sa.text("'cleaned'"))
        batch_op.alter_column('status',
               existing_type=sa.String(length=20),
               type_=mysql.ENUM('available', 'occupied', 'maintenance'),
               existing_nullable=True,
               existing_server_default=sa.text("'available'"))
        batch_op.alter_column('price_next_hour',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=mysql.INTEGER(),
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('initial_hours',
               existing_type=mysql.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'2'"))
        batch_op.alter_column('price_initial_block',
               existing_type=mysql.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('room_type',
               existing_type=sa.String(length=20),
               type_=mysql.ENUM('Standard', 'Deluxe', 'Suite'),
               existing_nullable=False)
        batch_op.drop_column('hotel_id')

    with op.batch_alter_table('price_rules', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('price_daily',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=mysql.INTEGER(),
               existing_nullable=False)
        batch_op.drop_column('hotel_id')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('booking_room_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('created_by', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('payments_ibfk_1'), 'bookings', ['booking_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_index('ix_payments_hotel_booking')
        batch_op.alter_column('payment_method',
               existing_type=sa.String(length=50),
               type_=mysql.ENUM('cash', 'banking', 'credit_card', 'qr_code', 'other'),
               existing_nullable=True,
               existing_server_default=sa.text("'cash'"))
        batch_op.drop_column('hotel_id')

    with op.batch_alter_table('inventory_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('_hotel_inv_code_uc', type_='unique')
        batch_op.create_index(batch_op.f('code'), ['code'], unique=True)
        batch_op.drop_column('hotel_id')

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('hotel_id')

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('_hotel_cccd_uc', type_='unique')
        batch_op.create_index(batch_op.f('phone'), ['phone'], unique=True)
        batch_op.create_index(batch_op.f('email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('cccd'), ['cccd'], unique=True)
        batch_op.alter_column('phone',
               existing_type=mysql.VARCHAR(length=15),
               nullable=False)
        batch_op.drop_column('hotel_id')

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index('ix_bookings_hotel_status')
        batch_op.create_index(batch_op.f('code'), ['code'], unique=True)
        batch_op.alter_column('status',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True,
               existing_server_default=sa.text("'pending'"))
        batch_op.alter_column('payment_status',
               existing_type=sa.String(length=20),
               type_=mysql.ENUM('unpaid', 'partial', 'paid', 'refunded'),
               existing_nullable=True,
               existing_server_default=sa.text("'partial'"))
        batch_op.drop_column('hotel_id')

    with op.batch_alter_table('booking_services', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('hotel_id')

    with op.batch_alter_table('booking_rooms', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('booking_rooms_ibfk_1'), 'bookings', ['booking_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_index('ix_booking_rooms_hotel_status')
        batch_op.drop_index('ix_booking_rooms_hotel_booking_status')
        batch_op.alter_column('status',
               existing_type=sa.String(length=20),
               type_=mysql.ENUM('booked', 'checked_in', 'checked_out', 'cancelled'),
               existing_nullable=True,
               existing_server_default=sa.text("'booked'"))
        batch_op.alter_column('rental_type',
               existing_type=sa.String(length=20),
               type_=mysql.ENUM('daily', 'hourly'),
               existing_nullable=True,
               existing_server_default=sa.text("'daily'"))
        batch_op.drop_column('hotel_id')

    op.drop_table('hotels')
    # ### end Alembic commands ###
